vich_uploader:
    db_driver: orm

    mappings:
        colleague_image:
            uri_prefix: /images/colleagues/
            upload_destination: '%kernel.project_dir%/public/images/colleagues'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
